fix: display formatting

diff --git a/Makefile.main.template b/Makefile.main.template
--- a/Makefile.main.template
+++ b/Makefile.main.template
@@ -16,8 +16,8 @@ $(COMMANDS):
 	@echo "Running $(YELLOW)'$@'$(RESET) for all projects."
 	@for proj in $(PROJECT_NAMES); do \
 		echo "\n----------------------------------------------"; \
-		echo "Processing $(GREEN)$$proj$(RESET)"; \
-		$(MAKE) -C $(TARGET_DIR)/$$proj $@ || exit 1; \
+		echo "Processing $(YELLOW)'$@'$(RESET) on $(GREEN)$$proj$(RESET)"; \
+		$(MAKE) --no-print-directory -C $(TARGET_DIR)/$$proj $@ || echo "$(RED)Failed$(RESET) to execute $(YELLOW)'$@'$(RESET) on $(GREEN)$$proj$(RESET)"; \
 		echo "----------------------------------------------\n"; \
 	done
 
